spring:
  application:
    name: im
  profiles:
    active: dev

# MyBatis配置
mybatis-plus:
  mapperLocations: classpath*:mapper/**/*.xml
  map-underscore-to-camel-case: true
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tmesh.im
  typeEnumsPackage: com.tmesh.im
  configuration:
    defaultEnumTypeHandler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    mapUnderscoreToCamelCase: true
    #日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cacheEnabled: true
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  # 合理化分页
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

# 日志配置
logging:
  group:
    tomcat: org.apache.catalina,org.apache.coyote,org.apache.tomcat
  level:
    com.tmesh: info
    org.springframework: info
    com.baomidou.example.mapper: info
    root: info
    sql: debug
    tomcat: info
    web: info